### ISSUE TITLE
Make source available in repository

### ISSUE THREAD

**Issue by rosalogia** [KuzniaZack/StreamToDonateAutoPlayer#1]
This application seems incredibly useful right now, but it's definitely considered unsafe to download and execute binary files off the internet. It would be way safer if alongside binary releases, the source code of the application was available for verification and manual compilation. Would that be possible?

**Comment by KuzniaZack** [comment]
This is an excellent suggestion, thank you. I realize now how unsafe throwing an executable file with no proof of its safety is and wasn't even thinking about that when I put it up! adding the source code now
